import { OptionsProp } from "@/lib/features/presets/PresetTypes";

export interface ListItem {
  id: keyof OptionsProp;
  title: string;
  options?: { title: string | number }[];
}

// Separate constant data
export const PRESET_OPTIONS: ListItem[] = [
  {
    id: "brollToggle",
    title: "broll Transition",
  },
  {
    id: "backgroundColor",
    title: "Select Background",
  },
  {
    id: "scaling",
    title: "Select Video Scaling",
  },
  {
    id: "filter",
    title: "Select Filter",
    options: [
      { title: "vivid_highlights" },
      { title: "clean_pop" },
      { title: "crisp_bright" },
      { title: "modern_pop" },
      { title: "retro_glow" },
      { title: "bright_bold" },
      { title: "cinematic_sharp" },
      { title: "neon_dream" },
      { title: "sharp_contrast" },
      { title: "sleek_fade" },
      { title: "vivid_glow" },
      { title: "high_contrast_dream" },
      { title: "golden_hour" },
      { title: "cinematic_contrast" },
      { title: "pop_art" },
      { title: "film_noir" },
      { title: "sleep_monochrome" },
      { title: "vibrant_bliss" },
      { title: "urban_chill" },
      { title: "neon_nights" },
      { title: "elegant_glow" },
      { title: "pop_color" },
      { title: "vintage_cool" },
      { title: "retro_glow" },
      { title: "crisp_clean" },
      { title: "vivid_dream" },
      { title: "cool_breeze" },
      { title: "luxe_gold" },
      { title: "monochrome_gold" },
      { title: "electric_blue" },
      { title: "rose_tint" },
      { title: "solar_flare" },
      { title: "city_lights" },
      { title: "sunset_vibes" },
      { title: "bold_bright" },
      { title: "crimson_tide" },
      { title: "frosted_glass" },
      { title: "sunlit_bloom" },
      { title: "cinematic_fade" },
      { title: "golden_hour" },
      { title: "neon_rush" },
      { title: "vibrant_pop" },
      { title: "urban_grind" },
      { title: "muted_vintage" },
      { title: "electric_sunset" },
      { title: "twilight_glow" },
      { title: "epic_fade" },
      { title: "film_noir_blackandwhite" },
      { title: "golden_fade" },
      { title: "dreamy_bokeh" },
      { title: "midnight_glow" },
      { title: "urban_lights" },
      { title: "mystic_shadows" },
      { title: "desert_mirage" },
      { title: "shadow_play" },
      { title: "twilight_drift" },
    ],
  },
  {
    id: "fontPosition",
    title: "Select Font Position",
    options: [{ title: "center" }, { title: "top" }, { title: "bottom" }],
  },
  {
    id: "aspectRatio",
    title: "Select Aspect Ratio",
    options: [
      { title: "1_1" },
      { title: "16_9" },
      { title: "4_3" },
      { title: "9_16" },
      { title: "3_4" },
      { title: "4_5" },
      { title: "5_4" },
      { title: "3_2" },
      { title: "2_3" },
      { title: "5_8" },
    ],
  },
  {
    id: "fontColor",
    title: "Select Font Color",
  },
  {
    id: "fontCapitalization",
    title: "Font Capitalization",
  },
  {
    id: "font",
    title: "Select Font",
    options: [
      { title: "Agency-FB" },
      { title: "Agency-FB-Bold" },
      { title: "Alef-Bold" },
      { title: "Alef-Regular" },
      { title: "Algerian" },
      { title: "Amiri-Bold" },
      { title: "Amiri-Bold-Italic" },
      { title: "Amiri-Italic" },
      { title: "Amiri-Quran-Regular" },
      { title: "Amiri-Regular" },
      { title: "Arial" },
      { title: "Arial-Black" },
      { title: "Arial-Bold" },
      { title: "Arial-Bold-Italic" },
      { title: "Arial-Italic" },
      { title: "Arial-Narrow" },
      { title: "Arial-Narrow-Bold" },
      { title: "Arial-Narrow-Bold-Italic" },
      { title: "Arial-Narrow-Italic" },
      { title: "Arial-Rounded-MT-Bold" },
      { title: "Bahnschrift" },
      { title: "Baskerville-Old-Face" },
      { title: "Bauhaus-93" },
      { title: "Bell-MT" },
      { title: "Bell-MT-Bold" },
      { title: "Bell-MT-Italic" },
      { title: "Berlin-Sans-FB" },
      { title: "Berlin-Sans-FB-Bold" },
      { title: "Berlin-Sans-FB-Demi-Bold" },
      { title: "Bernard-MT-Condensed" },
      { title: "Blackadder-ITC" },
      { title: "Bodoni-MT" },
      { title: "Bodoni-MT-Black" },
      { title: "Bodoni-MT-Black-Italic" },
      { title: "Bodoni-MT-Bold" },
      { title: "Bodoni-MT-Bold-Italic" },
      { title: "Bodoni-MT-Condensed" },
      { title: "Bodoni-MT-Condensed-Bold" },
      { title: "Bodoni-MT-Condensed-Bold-Italic" },
      { title: "Bodoni-MT-Condensed-Italic" },
      { title: "Bodoni-MT-Italic" },
      { title: "Bodoni-MT-Poster-Compressed" },
      { title: "Book-Antiqua" },
      { title: "Book-Antiqua-Bold" },
      { title: "Book-Antiqua-Bold-Italic" },
      { title: "Book-Antiqua-Italic" },
      { title: "Bookman-Old-Style" },
      { title: "Bookman-Old-Style-Bold" },
      { title: "Bookman-Old-Style-Bold-Italic" },
      { title: "Bookman-Old-Style-Italic" },
      { title: "Bookshelf-Symbol-7" },
      { title: "Bradley-Hand-ITC" },
      { title: "Britannic-Bold" },
      { title: "Broadway" },
      { title: "Brush-Script-MT-Italic" },
      { title: "Caladea" },
      { title: "Caladea-Bold" },
      { title: "Caladea-Bold-Italic" },
      { title: "Caladea-Italic" },
      { title: "Calibri" },
      { title: "Calibri-Bold" },
      { title: "Calibri-Bold-Italic" },
      { title: "Calibri-Italic" },
      { title: "Calibri-Light" },
      { title: "Calibri-Light-Italic" },
      { title: "Californian-FB" },
      { title: "Californian-FB-Bold" },
      { title: "Californian-FB-Italic" },
      { title: "Calisto-MT" },
      { title: "Calisto-MT-Bold" },
      { title: "Calisto-MT-Bold-Italic" },
      { title: "Calisto-MT-Italic" },
      { title: "Cambria-&-Cambria-Math" },
      { title: "Cambria-Bold" },
      { title: "Cambria-Bold-Italic" },
      { title: "Cambria-Italic" },
      { title: "Candara" },
      { title: "Candara-Bold" },
      { title: "Candara-Bold-Italic" },
      { title: "Candara-Italic" },
      { title: "Candara-Light" },
      { title: "Candara-Light-Italic" },
      { title: "Carlito" },
      { title: "Carlito-Bold" },
      { title: "Carlito-Bold-Italic" },
      { title: "Carlito-Italic" },
      { title: "Cascadia-Code-Regular" },
      { title: "Cascadia-Mono-Regular" },
      { title: "Castellar" },
      { title: "Centaur" },
      { title: "Century" },
      { title: "Century-Gothic" },
      { title: "Century-Gothic-Bold" },
      { title: "Century-Gothic-Bold-Italic" },
      { title: "Century-Gothic-Italic" },
      { title: "Century-Schoolbook" },
      { title: "Century-Schoolbook-Bold" },
      { title: "Century-Schoolbook-Bold-Italic" },
      { title: "Century-Schoolbook-Italic" },
      { title: "Chiller" },
      { title: "Colonna-MT" },
      { title: "Comic-Sans-MS" },
      { title: "Comic-Sans-MS-Bold" },
      { title: "Comic-Sans-MS-Bold-Italic" },
      { title: "Comic-Sans-MS-Italic" },
      { title: "Consolas" },
      { title: "Consolas-Bold" },
      { title: "Consolas-Bold-Italic" },
      { title: "Consolas-Italic" },
      { title: "Constantia" },
      { title: "Constantia-Bold" },
      { title: "Constantia-Bold-Italic" },
      { title: "Constantia-Italic" },
      { title: "Cooper-Black" },
      { title: "Copperplate-Gothic-Bold" },
      { title: "Copperplate-Gothic-Light" },
      { title: "Corbel" },
      { title: "Corbel-Bold" },
      { title: "Corbel-Bold-Italic" },
      { title: "Corbel-Italic" },
      { title: "Corbel-Light" },
      { title: "Corbel-Light-Italic" },
      { title: "Courier-New" },
      { title: "Courier-New-Bold" },
      { title: "Courier-New-Bold-Italic" },
      { title: "Courier-New-Italic" },
      { title: "Curlz-MT" },
      { title: "David-CLM-Bold" },
      { title: "David-CLM-Bold-Italic" },
      { title: "David-CLM-Medium" },
      { title: "David-CLM-Medium-Italic" },
      { title: "David-Libre-Bold" },
      { title: "David-Libre-Regular" },
      { title: "DejaVu-Sans" },
      { title: "DejaVu-Sans-Bold" },
      { title: "DejaVu-Sans-Bold-Oblique" },
      { title: "DejaVu-Sans-Condensed" },
      { title: "DejaVu-Sans-Condensed-Bold" },
      { title: "DejaVu-Sans-Condensed-Bold-Oblique" },
      { title: "DejaVu-Sans-Condensed-Oblique" },
      { title: "DejaVu-Sans-ExtraLight" },
      { title: "DejaVu-Sans-Mono" },
      { title: "DejaVu-Sans-Mono-Bold" },
      { title: "DejaVu-Sans-Mono-Bold-Oblique" },
      { title: "DejaVu-Sans-Mono-Oblique" },
      { title: "DejaVu-Sans-Oblique" },
      { title: "DejaVu-Serif" },
      { title: "DejaVu-Serif-Bold" },
      { title: "DejaVu-Serif-Bold-Italic" },
      { title: "DejaVu-Serif-Condensed" },
      { title: "DejaVu-Serif-Condensed-Bold" },
      { title: "DejaVu-Serif-Condensed-Bold-Italic" },
      { title: "DejaVu-Serif-Condensed-Italic" },
      { title: "DejaVu-Serif-Italic" },
      { title: "DejaVuMathTeXGyre-Regular" },
      { title: "Dubai-Bold" },
      { title: "Dubai-Light" },
      { title: "Dubai-Medium" },
      { title: "Dubai-Regular" },
      { title: "Ebrima" },
      { title: "Ebrima-Bold" },
      { title: "Edwardian-Script-ITC" },
      { title: "Elephant" },
      { title: "Elephant-Italic" },
      { title: "Engravers-MT" },
      { title: "Eras-Bold-ITC" },
      { title: "Eras-Demi-ITC" },
      { title: "Eras-Light-ITC" },
      { title: "Eras-Medium-ITC" },
      { title: "Felix-Titling" },
      { title: "Footlight-MT-Light" },
      { title: "Forte" },
      { title: "Frank-Ruehl-CLM-Bold" },
      { title: "Frank-Ruehl-CLM-Bold-Oblique" },
      { title: "Frank-Ruehl-CLM-Medium" },
      { title: "Frank-Ruehl-CLM-Medium-Oblique" },
      { title: "Frank-Ruhl-Hofshi-Bold" },
      { title: "Franklin-Gothic-Book" },
      { title: "Franklin-Gothic-Book-Italic" },
      { title: "Franklin-Gothic-Demi" },
      { title: "Franklin-Gothic-Demi-Cond" },
      { title: "Franklin-Gothic-Demi-Italic" },
      { title: "Franklin-Gothic-Heavy" },
      { title: "Franklin-Gothic-Heavy-Italic" },
      { title: "Franklin-Gothic-Medium" },
      { title: "Franklin-Gothic-Medium-Cond" },
      { title: "Franklin-Gothic-Medium-Italic" },
      { title: "FrankRuhlHofshi-Regular" },
      { title: "Freestyle-Script" },
      { title: "French-Script-MT" },
      { title: "Gabriola" },
      { title: "Gadugi" },
      { title: "Gadugi-Bold" },
      { title: "Garamond" },
      { title: "Garamond-Bold" },
      { title: "Garamond-Italic" },
      { title: "Gentium-Basic" },
      { title: "Gentium-Basic-Bold" },
      { title: "Gentium-Basic-Bold-Italic" },
      { title: "Gentium-Basic-Italic" },
      { title: "Gentium-Book-Basic" },
      { title: "Gentium-Book-Basic-Bold" },
      { title: "Gentium-Book-Basic-Bold-Italic" },
      { title: "Gentium-Book-Basic-Italic" },
      { title: "Georgia" },
      { title: "Georgia-Bold" },
      { title: "Georgia-Bold-Italic" },
      { title: "Georgia-Italic" },
      { title: "Gigi" },
      { title: "Gill-Sans-MT" },
      { title: "Gill-Sans-MT-Bold" },
      { title: "Gill-Sans-MT-Bold-Italic" },
      { title: "Gill-Sans-MT-Condensed" },
      { title: "Gill-Sans-MT-Ext-Condensed-Bold" },
      { title: "Gill-Sans-MT-Italic" },
      { title: "Gill-Sans-Ultra-Bold" },
      { title: "Gill-Sans-Ultra-Bold-Condensed" },
      { title: "Gloucester-MT-Extra-Condensed" },
      { title: "Goudy-Old-Style" },
      { title: "Goudy-Old-Style-Bold" },
      { title: "Goudy-Old-Style-Italic" },
      { title: "Goudy-Stout" },
      { title: "Haettenschweiler" },
      { title: "Harlow-Solid-Italic" },
      { title: "Harrington" },
      { title: "High-Tower-Text" },
      { title: "High-Tower-Text-Italic" },
      { title: "Holo-MDL2-Assets" },
      { title: "Impact" },
      { title: "Imprint-MT-Shadow" },
      { title: "Informal-Roman" },
      { title: "Ink-Free" },
      { title: "Javanese-Text" },
      { title: "Jokerman" },
      { title: "Juice-ITC" },
      { title: "Kristen-ITC" },
      { title: "Kunstler-Script" },
      { title: "Leelawadee-UI" },
      { title: "Leelawadee-UI-Bold" },
      { title: "Leelawadee-UI-Semilight" },
      { title: "Liberation-Mono" },
      { title: "Liberation-Mono-Bold" },
      { title: "Liberation-Mono-Bold-Italic" },
      { title: "Liberation-Mono-Italic" },
      { title: "Liberation-Sans" },
      { title: "Liberation-Sans-Bold" },
      { title: "Liberation-Sans-Bold-Italic" },
      { title: "Liberation-Sans-Italic" },
      { title: "Liberation-Sans-Narrow" },
      { title: "Liberation-Sans-Narrow-Bold" },
      { title: "Liberation-Sans-Narrow-Bold-Italic" },
      { title: "Liberation-Sans-Narrow-Italic" },
      { title: "Liberation-Serif" },
      { title: "Liberation-Serif-Bold" },
      { title: "Liberation-Serif-Bold-Italic" },
      { title: "Liberation-Serif-Italic" },
      { title: "Linux-Biolinum-G-Bold" },
      { title: "Linux-Biolinum-G-Italic" },
      { title: "Linux-Biolinum-G-Regular" },
      { title: "Linux-Libertine-G-Bold" },
      { title: "Linux-Libertine-G-Bold-Italic" },
      { title: "Linux-Libertine-G-Display-Regular" },
      { title: "Linux-Libertine-G-Italic" },
      { title: "Linux-Libertine-G-Regular" },
      { title: "Linux-Libertine-G-Semibold" },
      { title: "Linux-Libertine-G-Semibold-Italic" },
      { title: "Lucida-Bright" },
      { title: "Lucida-Bright-Demibold" },
      { title: "Lucida-Bright-Demibold-Italic" },
      { title: "Lucida-Bright-Italic" },
      { title: "Lucida-Calligraphy-Italic" },
      { title: "Lucida-Console" },
      { title: "Lucida-Fax-Demibold" },
      { title: "Lucida-Fax-Demibold-Italic" },
      { title: "Lucida-Fax-Italic" },
      { title: "Lucida-Fax-Regular" },
      { title: "Lucida-Handwriting-Italic" },
      { title: "Lucida-Sans-Demibold-Italic" },
      { title: "Lucida-Sans-Demibold-Roman" },
      { title: "Lucida-Sans-Italic" },
      { title: "Lucida-Sans-Regular" },
      { title: "Lucida-Sans-Typewriter-Bold" },
      { title: "Lucida-Sans-Typewriter-Bold-Oblique" },
      { title: "Lucida-Sans-Typewriter-Oblique" },
      { title: "Lucida-Sans-Typewriter-Regular" },
      { title: "Lucida-Sans-Unicode" },
      { title: "Magneto-Bold" },
      { title: "Maiandra-GD" },
      { title: "Malgun-Gothic" },
      { title: "Malgun-Gothic-Bold" },
      { title: "Malgun-Gothic-SemiLight" },
      { title: "Matura-MT-Script-Capitals" },
      { title: "Microsoft-Himalaya" },
      { title: "Microsoft-JhengHei-&-Microsoft-JhengHei-UI" },
      { title: "Microsoft-JhengHei-Bold-&-Microsoft-JhengHei-UI-Bold" },
      { title: "Microsoft-JhengHei-Light-&-Microsoft-JhengHei-UI-Light" },
      { title: "Microsoft-New-Tai-Lue" },
      { title: "Microsoft-New-Tai-Lue-Bold" },
      { title: "Microsoft-PhagsPa" },
      { title: "Microsoft-PhagsPa-Bold" },
      { title: "Microsoft-Sans-Serif" },
      { title: "Microsoft-Tai-Le" },
      { title: "Microsoft-Tai-Le-Bold" },
      { title: "Microsoft-YaHei-&-Microsoft-YaHei-UI" },
      { title: "Microsoft-YaHei-Bold-&-Microsoft-YaHei-UI-Bold" },
      { title: "Microsoft-YaHei-Light-&-Microsoft-YaHei-UI-Light" },
      { title: "Microsoft-Yi-Baiti" },
      { title: "MingLiU-ExtB-&-PMingLiU-ExtB-&-MingLiU_HKSCS-ExtB" },
      { title: "Miriam-CLM-Bold" },
      { title: "Miriam-CLM-Book" },
      { title: "Miriam-Libre-Bold" },
      { title: "Miriam-Mono-CLM-Bold" },
      { title: "Miriam-Mono-CLM-Bold-Oblique" },
      { title: "Miriam-Mono-CLM-Book" },
      { title: "Miriam-Mono-CLM-Book-Oblique" },
      { title: "MiriamLibre-Regular" },
      { title: "Mistral" },
      { title: "Modern-No.-20" },
      { title: "Mongolian-Baiti" },
      { title: "Monotype-Corsiva" },
      { title: "MS-Gothic-&-MS-UI-Gothic-&-MS-PGothic" },
      { title: "MS-Outlook" },
      { title: "MS-Reference-Sans-Serif" },
      { title: "MS-Reference-Specialty" },
      { title: "MT-Extra" },
      { title: "MV-Boli" },
      { title: "Myanmar-Text" },
      { title: "Myanmar-Text-Bold" },
      { title: "Nachlieli-CLM-Bold" },
      { title: "Nachlieli-CLM-Bold-Oblique" },
      { title: "Nachlieli-CLM-Light" },
      { title: "Nachlieli-CLM-Light-Oblique" },
      { title: "Niagara-Engraved" },
      { title: "Niagara-Solid" },
      { title: "Noto-Kufi-Arabic" },
      { title: "Noto-Kufi-Arabic-Bold" },
      { title: "Noto-Mono" },
      { title: "Noto-Naskh-Arabic" },
      { title: "Noto-Naskh-Arabic-Bold" },
      { title: "Noto-Naskh-Arabic-UI" },
      { title: "Noto-Naskh-Arabic-UI-Bold" },
      { title: "Noto-Sans-Arabic-Bold" },
      { title: "Noto-Sans-Arabic-Regular" },
      { title: "Noto-Sans-Arabic-UI-Bold" },
      { title: "Noto-Sans-Arabic-UI-Regular" },
      { title: "Noto-Sans-Armenian-Bold" },
      { title: "Noto-Sans-Armenian-Regular" },
      { title: "Noto-Sans-Bold" },
      { title: "Noto-Sans-Bold-Italic" },
      { title: "Noto-Sans-Condensed" },
      { title: "Noto-Sans-Condensed-Bold" },
      { title: "Noto-Sans-Condensed-Bold-Italic" },
      { title: "Noto-Sans-Condensed-Italic" },
      { title: "Noto-Sans-Georgian-Bold" },
      { title: "Noto-Sans-Georgian-Regular" },
      { title: "Noto-Sans-Hebrew-Bold" },
      { title: "Noto-Sans-Hebrew-Regular" },
      { title: "Noto-Sans-Italic" },
      { title: "Noto-Sans-Lao-Bold" },
      { title: "Noto-Sans-Lao-Regular" },
      { title: "Noto-Sans-Light" },
      { title: "Noto-Sans-Light-Italic" },
      { title: "Noto-Sans-Lisu-Regular" },
      { title: "Noto-Sans-Regular" },
      { title: "Noto-Serif-Armenian-Bold" },
      { title: "Noto-Serif-Armenian-Regular" },
      { title: "Noto-Serif-Bold" },
      { title: "Noto-Serif-Bold-Italic" },
      { title: "Noto-Serif-Condensed" },
      { title: "Noto-Serif-Condensed-Bold" },
      { title: "Noto-Serif-Condensed-Bold-Italic" },
      { title: "Noto-Serif-Condensed-Italic" },
      { title: "Noto-Serif-Georgian-Bold" },
      { title: "Noto-Serif-Georgian-Regular" },
      { title: "Noto-Serif-Hebrew-Bold" },
      { title: "Noto-Serif-Hebrew-Regular" },
      { title: "Noto-Serif-Italic" },
      { title: "Noto-Serif-Lao-Bold" },
      { title: "Noto-Serif-Lao-Regular" },
      { title: "Noto-Serif-Light" },
      { title: "Noto-Serif-Light-Italic" },
      { title: "Noto-Serif-Regular" },
      { title: "OCR-A-Extended" },
      { title: "Old-English-Text-MT" },
      { title: "Onyx" },
      { title: "OpenSymbol" },
      { title: "Palace-Script-MT" },
      { title: "Palatino-Linotype" },
      { title: "Palatino-Linotype-Bold" },
      { title: "Palatino-Linotype-Bold-Italic" },
      { title: "Palatino-Linotype-Italic" },
      { title: "Papyrus" },
      { title: "Parchment" },
      { title: "Perpetua" },
      { title: "Perpetua-Bold" },
      { title: "Perpetua-Bold-Italic" },
      { title: "Perpetua-Italic" },
      { title: "Perpetua-Titling-MT-Bold" },
      { title: "Perpetua-Titling-MT-Light" },
      { title: "Playbill" },
      { title: "Poor-Richard" },
      { title: "Pristina" },
      { title: "Rage-Italic" },
      { title: "Ravie" },
      { title: "Reem-Kufi-Bold" },
      { title: "Reem-Kufi-Regular" },
      { title: "Rockwell" },
      { title: "Rockwell-Bold" },
      { title: "Rockwell-Bold-Italic" },
      { title: "Rockwell-Condensed" },
      { title: "Rockwell-Condensed-Bold" },
      { title: "Rockwell-Extra-Bold" },
      { title: "Rockwell-Italic" },
      { title: "Rubik-Bold" },
      { title: "Rubik-Bold-Italic" },
      { title: "Rubik-Italic" },
      { title: "Rubik-Regular" },
      { title: "Sans-Serif-Collection" },
      { title: "Scheherazade" },
      { title: "Scheherazade-Bold" },
      { title: "Script-MT-Bold" },
      { title: "Segoe-Fluent-Icons" },
      { title: "Segoe-MDL2-Assets" },
      { title: "Segoe-Print" },
      { title: "Segoe-Print-Bold" },
      { title: "Segoe-Script" },
      { title: "Segoe-Script-Bold" },
      { title: "Segoe-UI" },
      { title: "Segoe-UI-Black" },
      { title: "Segoe-UI-Black-Italic" },
      { title: "Segoe-UI-Bold" },
      { title: "Segoe-UI-Bold-Italic" },
      { title: "Segoe-UI-Emoji" },
      { title: "Segoe-UI-Historic" },
      { title: "Segoe-UI-Italic" },
      { title: "Segoe-UI-Light" },
      { title: "Segoe-UI-Light-Italic" },
      { title: "Segoe-UI-Semibold" },
      { title: "Segoe-UI-Semibold-Italic" },
      { title: "Segoe-UI-Semilight" },
      { title: "Segoe-UI-Semilight-Italic" },
      { title: "Segoe-UI-Symbol" },
      { title: "Segoe-UI-Variable" },
      { title: "Showcard-Gothic" },
      { title: "SimSun-&-NSimSun" },
      { title: "SimSun-ExtB" },
      { title: "SimSun-ExtG" },
      { title: "Sitka-Text" },
      { title: "Sitka-Text-Italic" },
      { title: "Snap-ITC" },
      { title: "Source-Sans-Pro" },
      { title: "Source-Sans-Pro-Black" },
      { title: "Source-Sans-Pro-Black-Italic" },
      { title: "Source-Sans-Pro-Bold" },
      { title: "Source-Sans-Pro-Bold-Italic" },
      { title: "Source-Sans-Pro-ExtraLight" },
      { title: "Source-Sans-Pro-ExtraLight-Italic" },
      { title: "Source-Sans-Pro-Italic" },
      { title: "Source-Sans-Pro-Light" },
      { title: "Source-Sans-Pro-Light-Italic" },
      { title: "Source-Sans-Pro-Semibold" },
      { title: "Source-Sans-Pro-Semibold-Italic" },
      { title: "Stencil" },
      { title: "Sylfaen" },
      { title: "Symbol" },
      { title: "Tahoma" },
      { title: "Tahoma-Bold" },
      { title: "Tempus-Sans-ITC" },
      { title: "Times-New-Roman" },
      { title: "Times-New-Roman-Bold" },
      { title: "Times-New-Roman-Bold-Italic" },
      { title: "Times-New-Roman-Italic" },
      { title: "Trebuchet-MS" },
      { title: "Trebuchet-MS-Bold" },
      { title: "Trebuchet-MS-Bold-Italic" },
      { title: "Trebuchet-MS-Italic" },
      { title: "Tw-Cen-MT" },
      { title: "Tw-Cen-MT-Bold" },
      { title: "Tw-Cen-MT-Bold-Italic" },
      { title: "Tw-Cen-MT-Condensed" },
      { title: "Tw-Cen-MT-Condensed-Bold" },
      { title: "Tw-Cen-MT-Condensed-Extra-Bold" },
      { title: "Tw-Cen-MT-Italic" },
      { title: "Verdana" },
      { title: "Verdana-Bold" },
      { title: "Verdana-Bold-Italic" },
      { title: "Verdana-Italic" },
      { title: "Viner-Hand-ITC" },
      { title: "Vivaldi-Italic" },
      { title: "Vladimir-Script" },
      { title: "Webdings" },
      { title: "Wide-Latin" },
      { title: "Wingdings" },
      { title: "Wingdings-2" },
      { title: "Wingdings-3" },
      { title: "Yu-Gothic-Bold-&-Yu-Gothic-UI-Semibold-&-Yu-Gothic-UI-Bold" },
      { title: "Yu-Gothic-Light-&-Yu-Gothic-UI-Light" },
      { title: "Yu-Gothic-Medium-&-Yu-Gothic-UI-Regular" },
      { title: "Yu-Gothic-Regular-&-Yu-Gothic-UI-Semilight" },
    ],
  },
  {
    id: "fontSize",
    title: "Select Font Size",
    options: [{ title: "Small" }, { title: "Medium" }, { title: "Large" }],
  },
  {
    id: "strokeColor",
    title: "Select Stroke Color",
  },
  {
    id: "strokeWidth",
    title: "Select Stroke Width",
    options: [
      { title: "None" },
      { title: "Thin" },
      { title: "Regular" },
      { title: "Semibold" },
      { title: "Bold" },
    ],
  },
  {
    id: "glowColor",
    title: "Select Glow Color",
  },
  {
    id: "shadowWidth",
    title: "Select Shadow Width",
    options: [
      { title: "None" },
      { title: "Thin" },
      { title: "Regular" },
      { title: "Semibold" },
      { title: "Bold" },
    ],
  },
];

export const DEFAULT_OPTIONS: OptionsProp = {
  filter: null,
  font: null,
  fontSize: null,
  backgroundColor: "#ffffff",
  fontPosition: null,
  aspectRatio: null,
  fontColor: "#ffffff",
  scaling: 100,
  brollToggle: true,
  fontCapitalization: false,
  strokeColor: "#000000",
  strokeWidth: null,
  glowColor: "#ffffff",
  shadowWidth: null,
};
